"""
PURPOSE: Constants and enumerations for JSR Hydra trading system.

This module defines all enums and constant values used throughout the
JSR Hydra trading system, including market regimes, order statuses,
strategies, and supported trading symbols.
"""

from enum import Enum
from typing import Dict


class RegimeType(str, Enum):
    """
    PURPOSE: Market regime classification for adaptive trading strategies.

    Represents different market conditions that may require different
    trading approaches and risk management parameters.
    """

    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGING = "RANGING"
    VOLATILE = "VOLATILE"
    QUIET = "QUIET"
    TRANSITIONING = "TRANSITIONING"


class OrderDirection(str, Enum):
    """
    PURPOSE: Trade direction indicators.

    Specifies whether a trade is a buy or sell operation.
    """

    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(str, Enum):
    """
    PURPOSE: Order lifecycle states.

    Tracks the various states an order passes through from creation
    to completion or cancellation.
    """

    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class StrategyCode(str, Enum):
    """
    PURPOSE: Trading strategy identifiers.

    Enumerates the available trading strategies that can be executed
    by the JSR Hydra system.
    """

    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"


class StrategyStatus(str, Enum):
    """
    PURPOSE: Strategy execution states.

    Indicates the current operational state of a trading strategy.
    """

    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ERROR = "ERROR"
    STOPPED = "STOPPED"


class SystemStatus(str, Enum):
    """
    PURPOSE: Overall system operational states.

    Indicates the health and operational mode of the entire JSR Hydra system.
    """

    RUNNING = "RUNNING"
    HALTED = "HALTED"
    MAINTENANCE = "MAINTENANCE"


class Severity(str, Enum):
    """
    PURPOSE: Event and alert severity levels.

    Categorizes the importance and urgency of system events and alerts.
    """

    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class EventType(str, Enum):
    """
    PURPOSE: Event type classifications for system monitoring and logging.

    Defines all possible event types that can be generated by the
    JSR Hydra system during normal operation.
    """

    TRADE_OPENED = "TRADE_OPENED"
    TRADE_CLOSED = "TRADE_CLOSED"
    TRADE_MODIFIED = "TRADE_MODIFIED"
    TRADE_REJECTED = "TRADE_REJECTED"
    REGIME_CHANGED = "REGIME_CHANGED"
    ALLOCATION_CHANGED = "ALLOCATION_CHANGED"
    MODEL_RETRAINED = "MODEL_RETRAINED"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
    KILL_SWITCH_RESET = "KILL_SWITCH_RESET"
    DAILY_LIMIT_HIT = "DAILY_LIMIT_HIT"
    WEEKLY_LIMIT_HIT = "WEEKLY_LIMIT_HIT"
    MONTHLY_LIMIT_HIT = "MONTHLY_LIMIT_HIT"
    MT5_CONNECTED = "MT5_CONNECTED"
    MT5_DISCONNECTED = "MT5_DISCONNECTED"
    MT5_CONNECTION_ERROR = "MT5_CONNECTION_ERROR"
    ENGINE_STARTED = "ENGINE_STARTED"
    ENGINE_STOPPED = "ENGINE_STOPPED"
    STRATEGY_STARTED = "STRATEGY_STARTED"
    STRATEGY_PAUSED = "STRATEGY_PAUSED"
    STRATEGY_ERROR = "STRATEGY_ERROR"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    HEARTBEAT_MISSED = "HEARTBEAT_MISSED"
    CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED"


# Maximum drawdown percentage before triggering kill switch
MaxDrawdownPct: float = 15.0

# Daily loss limit percentage
DailyLossLimitPct: float = 5.0

# Maximum lot size for testing/live (safety cap)
MAX_TEST_LOTS: float = 0.01

# Supported trading symbols
SUPPORTED_SYMBOLS: list[str] = ["XAUUSD", "BTCUSD", "EURUSD", "GBPUSD", "USDJPY"]

# Timeframe mappings
TIMEFRAMES: Dict[str, str] = {
    "M1": "M1",
    "M5": "M5",
    "M15": "M15",
    "H1": "H1",
    "H4": "H4",
    "D1": "D1",
}
