"""
PURPOSE: Strategy signal models for JSR Hydra trading system.

Defines StrategySignal model for representing trading signals
generated by strategies, with validation for direction, confidence,
and price levels.
"""

from pydantic import BaseModel, field_validator
from typing import Optional


class StrategySignal(BaseModel):
    """
    PURPOSE: Represents a trading signal generated by a strategy.

    Encapsulates all information needed to execute a trade based on
    a strategy's analysis: direction, price targets, confidence level,
    and reasoning.

    CALLED BY:
        - strategies/base.py → run_cycle()
        - strategies/strategy_b.py → generate_signal()
        - engine/orchestrator.py → process signal

    Attributes:
        direction: BUY or SELL
        confidence: 0.0 to 1.0 probability score
        sl_price: Stop-loss price level
        tp_price: Take-profit price level
        reason: Human-readable explanation
        strategy_code: Strategy identifier (A, B, C, D, E)
    """

    direction: str
    confidence: float
    sl_price: float
    tp_price: float
    reason: str
    strategy_code: str

    @field_validator('direction')
    @classmethod
    def validate_direction(cls, v: str) -> str:
        """
        PURPOSE: Ensure direction is valid BUY or SELL.

        CALLED BY: Pydantic validation
        """
        if v.upper() not in ('BUY', 'SELL'):
            raise ValueError('direction must be either BUY or SELL')
        return v.upper()

    @field_validator('confidence')
    @classmethod
    def validate_confidence(cls, v: float) -> float:
        """
        PURPOSE: Ensure confidence is between 0 and 1.

        CALLED BY: Pydantic validation
        """
        if not 0.0 <= v <= 1.0:
            raise ValueError('confidence must be between 0.0 and 1.0')
        return v

    @field_validator('sl_price')
    @classmethod
    def validate_sl_price(cls, v: float) -> float:
        """
        PURPOSE: Ensure stop-loss price is positive.

        CALLED BY: Pydantic validation
        """
        if v <= 0:
            raise ValueError('sl_price must be greater than 0')
        return v

    @field_validator('tp_price')
    @classmethod
    def validate_tp_price(cls, v: float) -> float:
        """
        PURPOSE: Ensure take-profit price is positive.

        CALLED BY: Pydantic validation
        """
        if v <= 0:
            raise ValueError('tp_price must be greater than 0')
        return v
